server:
  port: 8088
spring:
  datasource:
    # url: jdbc:h2:~/test
    # 内存模式连接配置 库名: test
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  sql:
    init:
      data-locations: classpath*:schema-all.sql
      username: sa
      password: 123

  jpa:
    database: h2
    hibernate:
      # 每次启动对应实体
      ddl-auto: update
    show-sql: true
    open-in-view: false
  h2:
    console:
      # h2访问路径上下文。 通过 程序URl/h2-console 访问h2 web console
      path: /h2-console
      # 开启console访问 默认false
      enabled: true
      settings:
        # 开启h2 console 跟踪 方便调试  默认 false
        trace: false
        # 配置h2的远程访问 默认false
        web-allow-others: true
